"""原理图文本生成器

OrCAD Capture 使用 .DSN + .OLB 描述原理图,但底层都是文本格式。
本模块支持:
- 生成 PSpice/SPICE 网表(向后兼容 Allegro 的 netin)
- 生成 .DSN 工程文件 (Tcl/Mini-XML 格式)
- 简单电路 DSL → SPICE 转换
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Union


# ============================================================
# 简单电路 DSL
# ============================================================
#
# 语法(类似 SPICE 但更易用):
#   V1 in 0 SIN(0 5 1k)
#   R1 in out 1k
#   C1 out 0 1n
#   .TRAN 1us 3ms
#   .PROBE
#

def parse_circuit_dsl(text: str) -> Dict[str, object]:
    """把类 SPICE 的 DSL 文本解析为字典。

    Returns
    -------
    dict: {
        "components": [{"id": "R1", "type": "R", "nodes": ["in","out"], "value": "1k"}],
        "directives": [".TRAN 1us 3ms"],
        "models": ["D1N4148 ..."],
        "raw_lines": [...]
    }
    """
    components: List[Dict] = []
    directives: List[str] = []
    models: List[str] = []
    raw: List[str] = []

    type_map = {"V": "voltage_source", "I": "current_source",
                "R": "resistor", "C": "capacitor", "L": "inductor",
                "D": "diode", "Q": "bjt", "M": "mosfet",
                "X": "subcircuit", "E": "vcvs", "F": "cccs",
                "G": "vccs", "H": "ccvs", "B": "behavioral"}

    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("*"):
            raw.append(s)
            continue
        if s.startswith("."):
            directives.append(s)
            raw.append(s)
            continue
        m = re.match(r"^([A-Za-z])([A-Za-z0-9_]+)\s+(.*)$", s)
        if m:
            comp_type = m.group(1).upper()
            comp_id = m.group(2)
            rest = m.group(3).strip()
            tokens = rest.split()
            if comp_type in type_map and tokens:
                comp: Dict[str, object] = {
                    "id": comp_id,
                    "type": type_map[comp_type],
                    "raw_type": comp_type,
                    "nodes": [],
                    "value": None,
                    "model": None,
                    "extra": "",
                }
                # 找节点前缀
                idx = 0
                while idx < len(tokens) and re.match(r"^[a-zA-Z][a-zA-Z0-9_]*$", tokens[idx]):
                    comp["nodes"].append(tokens[idx])
                    idx += 1
                if idx < len(tokens):
                    comp["value"] = tokens[idx]
                    if idx + 1 < len(tokens):
                        if comp_type == "D":
                            comp["model"] = tokens[idx + 1]
                        comp["extra"] = " ".join(tokens[idx + 1:])
                components.append(comp)
        raw.append(s)

    return {
        "components": components,
        "directives": directives,
        "models": models,
        "raw_lines": raw,
    }


def netlist_from_dsl(dsl_text: str, include_probe: bool = True) -> str:
    """把 DSL 直接标准化为 PSpice/ngspice 兼容的网表"""
    parsed = parse_circuit_dsl(dsl_text)
    out: List[str] = ["* Generated by CadenceAI MCP"]
    out.extend(parsed["raw_lines"])
    if include_probe and not any(d.lower().startswith(".probe") for d in parsed["directives"]):
        out.append(".PROBE")
    if not any(d.lower() == ".end" for d in parsed["directives"]):
        out.append(".END")
    return "\n".join(out) + "\n"


# ============================================================
# OrCAD Capture .DSN 文本生成
# ============================================================

DSN_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<Project xmlns="http://www.cadence.com/orcad/capture/17.2"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Design Hierarchy>
    <Root Schematic="root" Path="{project_name}.DSN">
      <Sheet PageNumber="1">
        <Title>{title}</Title>
        <Author>{author}</Author>
        <Date>{date}</Date>
        <DocumentNumber>AI-GENERATED</DocumentNumber>
        <Revision>1.0</Revision>
      </Sheet>
    </Root>
  </Design Hierarchy>
  <Components>
{components}
  </Components>
  <Nets>
{nets}
  </Nets>
</Project>
"""


def generate_dsn(components: List[Dict[str, object]], nets: List[Dict[str, object]],
                 project_name: str = "ai_design", title: str = "AI-Generated Schematic",
                 author: str = "CadenceAI", date: str = "") -> str:
    """生成 OrCAD Capture 兼容的 DSN 工程文本(简化版)"""
    if not date:
        from datetime import date as _date
        date = _date.today().isoformat()
    comp_lines = []
    for i, c in enumerate(components):
        comp_lines.append(
            f'    <Component Part="{c.get("ref", "U" + str(i))}" '
            f'Value="{c.get("value", "")}" '
            f'X="{i*100}" Y="0" />'
        )
    net_lines = []
    for i, n in enumerate(nets):
        nodes = n.get("nodes", [])
        net_lines.append(f'    <Net Name="{n.get("name", "N" + str(i))}" Refdes="N{i}">')
        for node in nodes:
            net_lines.append(f'      <Pin Refdes="{node}" />')
        net_lines.append("    </Net>")
    return DSN_HEADER.format(
        project_name=project_name,
        title=title,
        author=author,
        date=date,
        components="\n".join(comp_lines),
        nets="\n".join(net_lines),
    )


# ============================================================
# 标准网表 -> 网表组整理 (用于 Allegro netin)
# ============================================================

def to_allegro_netlist(spice_netlist: str) -> str:
    """把 SPICE 网表转成 Allegro 可识别的物理网表(简化 TEMPLATE)。

    Allegro netin 接受 .tel (Telesis) 或 .mdb 格式。
    这里生成 .tel 风格的简化物理网表,仅做 AI 工作流演示。
    """
    lines = ["$ AI-Generated Physical Netlist for Allegro netin"]
    lines.append("$ Created by CadenceAI MCP")
    for raw in spice_netlist.splitlines():
        s = raw.strip()
        if not s or s.startswith("*") or s.startswith("."):
            continue
        m = re.match(r"^([A-Za-z])([A-Za-z0-9_]+)\s+(.*)$", s)
        if not m:
            continue
        comp_type, comp_id, rest = m.group(1), m.group(2), m.group(3).strip()
        tokens = rest.split()
        if comp_type in {"V", "I"}:
            continue  # 跳过源
        nodes, value = [], "0"
        idx = 0
        while idx < len(tokens) and re.match(r"^[a-zA-Z][a-zA-Z0-9_]*$", tokens[idx]):
            nodes.append(tokens[idx])
            idx += 1
        if idx < len(tokens):
            value = tokens[idx]
        if nodes:
            lines.append(f"{comp_type}{comp_id}  {nodes[0]}  {nodes[-1]}  {value}")
    return "\n".join(lines) + "\n"